apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  restartPolicy: Never
  containers:
  - name: motor
    image: busybox
    resources:
      limits:
        cpu: 100m
        memory: 16Mi
      requests:
        cpu: 100m
        memory: 16Mi
    command: ["sh", "-c"]
    args:
    - |
      echo Start.

      while true
      do
          date
          sleep 1
      done
  - name: sidecar
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo The Pod is running && sleep 10']
    resources:
      limits:
        cpu: 100m
        memory: 16Mi
      requests:
        cpu: 100m
        memory: 16Mi