apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-check
spec:
  restartPolicy: Never
  initContainers:
  - name: init
    image: busybox
    command: ["sh", "-c"]
    args:
    - |
      echo Start at `date`
      echo "This is pending phase"
      sleep 30;
      echo End at `date`.
      exit 0
  containers:
  - name: motor
    image: busybox
    resources:
      limits:
        cpu: 100m
        memory: 16Mi
      requests:
        cpu: 100m
        memory: 16Mi
    command: ["sh", "-c"]
    args:
    - |
      echo "This is runnning phase"
      while true
      do
          date
          sleep 1
      done
