apiVersion: v1
kind: Pod
metadata:
  name: single-container-pod
spec:
  restartPolicy: Never
  containers:
  - name: motor
    image: busybox
    resources:
      limits:
        cpu: 100m
        memory: 16Mi
      requests:
        cpu: 100m
        memory: 16Mi
    command: ["sh", "-c"]
    args:
    - |
      echo Start.

      while true
      do
          date
          sleep 1
      done
