apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: busybox
    name: test-container
    resources:
      limits:
        cpu: 100m
        memory: 16Mi
      requests:
        cpu: 100m
        memory: 16Mi
    command: ["sh", "-c"]
    args:
    - |
      echo "This is runnning phase"
      while true
      do
          date
          sleep 10
      done
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: DirectoryOrCreate

---

apiVersion: v1
kind: Pod
metadata:
  name: test-pd2
spec:
  containers:
  - image: busybox
    name: test-container2
    resources:
      limits:
        cpu: 100m
        memory: 16Mi
      requests:
        cpu: 100m
        memory: 16Mi
    command: ["sh", "-c"]
    args:
    - |
      echo "This is runnning phase"
      while true
      do
          date
          sleep 10
      done
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: DirectoryOrCreate